### Label Encoder

In [1]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [2]:
data =pd.read_csv("iris.csv",index_col=0)

In [3]:
#Changes does not effect the "data" dataframe
data1=data.copy()

In [4]:
data1.head()

       Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
sr.no
1               5.1          3.5           1.4          0.2  setosa
2               4.9          3.0           1.4          0.2  setosa
3               4.7          3.2           1.3          0.2  setosa
4               4.6          3.1           1.5          0.2  setosa
5               5.0          3.6           1.4          0.2  setosa

In [5]:
labelencoder = LabelEncoder()

In [6]:
data1.iloc[:, -1] = labelencoder.fit_transform(data1.iloc[:,-1])

In [7]:
data1.head()

       Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
sr.no
1               5.1          3.5           1.4          0.2        0
2               4.9          3.0           1.4          0.2        0
3               4.7          3.2           1.3          0.2        0
4               4.6          3.1           1.5          0.2        0
5               5.0          3.6           1.4          0.2        0

In [8]:
data1.tail()

       Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
sr.no
146             6.7          3.0           5.2          2.3        2
147             6.3          2.5           5.0          1.9        2
148             6.5          3.0           5.2          2.0        2
149             6.2          3.4           5.4          2.3        2
150             5.9          3.0           5.1          1.8        2

### One Hot Encoder

#### Using sklearn

In [9]:
from sklearn.preprocessing import OneHotEncoder

In [10]:
data2=data.copy()

In [13]:
# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')

In [14]:
# passing bridge-types-cat column (label encoded values of bridge_types)
enc_df = pd.DataFrame(enc.fit_transform(data2[['Species']]).toarray())

In [15]:
# merge with main df bridge_df on key values
data_final = data2.join(enc_df)
data_final

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species,0,1,2
sr.no,,,,,,,,
1,5.1,3.5,1.4,0.2,setosa,1.0,0.0,0.0
2,4.9,3.0,1.4,0.2,setosa,1.0,0.0,0.0
3,4.7,3.2,1.3,0.2,setosa,1.0,0.0,0.0
4,4.6,3.1,1.5,0.2,setosa,1.0,0.0,0.0
5,5.0,3.6,1.4,0.2,setosa,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...
146,6.7,3.0,5.2,2.3,virginica,0.0,0.0,1.0
147,6.3,2.5,5.0,1.9,virginica,0.0,0.0,1.0
148,6.5,3.0,5.2,2.0,virginica,0.0,0.0,1.0
149,6.2,3.4,5.4,2.3,virginica,0.0,0.0,1.0
150,5.9,3.0,5.1,1.8,virginica,NaN,NaN,NaN

#### Using Pandas

In [16]:
import pandas as pd

In [17]:
data3=data.copy()

In [18]:
data_encoded=pd.get_dummies(data3)

In [19]:
data_encoded

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica
sr.no,,,,,,,
1,5.1,3.5,1.4,0.2,1,0,0
2,4.9,3.0,1.4,0.2,1,0,0
3,4.7,3.2,1.3,0.2,1,0,0
4,4.6,3.1,1.5,0.2,1,0,0
5,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
146,6.7,3.0,5.2,2.3,0,0,1
147,6.3,2.5,5.0,1.9,0,0,1
148,6.5,3.0,5.2,2.0,0,0,1
149,6.2,3.4,5.4,2.3,0,0,1
150,5.9,3.0,5.1,1.8,0,0,1

#### IsolationForest

In [20]:
from sklearn.ensemble import IsolationForest

In [21]:
data =pd.read_csv("iris.csv",index_col=0)
data_encoded=pd.get_dummies(data)

In [22]:
# training the model
clf = IsolationForest(random_state=10,contamination=.01)
clf.fit(data_encoded)

IsolationForest(behaviour='deprecated', bootstrap=False, contamination=0.01,
                max_features=1.0, max_samples='auto', n_estimators=100,
                n_jobs=None, random_state=10, verbose=0, warm_start=False)

In [23]:
# predictions
y_pred_outliers = clf.predict(data_encoded)

In [24]:
#-1 for outliers and 1 for inliers.
y_pred_outliers

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [25]:
## Let us add a new data point which is outlier
data_encoded.loc[150]=[20,40,30,50,1,0,0]

In [26]:
# training the model
clf = IsolationForest(random_state=10,contamination=.01)
clf.fit(data_encoded)
# predictions
y_pred_outliers = clf.predict(data_encoded)
y_pred_outliers

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1])

In [27]:
data_encoded['scores']=clf.decision_function(data_encoded)

In [28]:
data_encoded['anomaly']=clf.predict(data_encoded.iloc[:,0:7])

In [29]:
data_encoded

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica,scores,anomaly
sr.no,,,,,,,,,
1,5.1,3.5,1.4,0.2,1,0,0,0.202073,1
2,4.9,3.0,1.4,0.2,1,0,0,0.185411,1
3,4.7,3.2,1.3,0.2,1,0,0,0.174012,1
4,4.6,3.1,1.5,0.2,1,0,0,0.182873,1
5,5.0,3.6,1.4,0.2,1,0,0,0.199432,1
...,...,...,...,...,...,...,...,...,...
146,6.7,3.0,5.2,2.3,0,0,1,0.164313,1
147,6.3,2.5,5.0,1.9,0,0,1,0.133436,1
148,6.5,3.0,5.2,2.0,0,0,1,0.179224,1
149,6.2,3.4,5.4,2.3,0,0,1,0.125229,1
150,20.0,40.0,30.0,50.0,1,0,0,-0.287374,-1

In [30]:
#Print the outlier data points
data_encoded[data_encoded['anomaly']==-1]

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica,scores,anomaly
sr.no,,,,,,,,,
107,4.9,2.5,4.5,1.7,0,0,1,-0.009111,-1
150,20.0,40.0,30.0,50.0,1,0,0,-0.287374,-1

### PPS score

In [ ]:
#install the package
#!pip install ppscore

In [31]:
import ppscore as pps
#pps.score(df, "feature_column", "target_column")  syntax
pps.score(data, "Sepal.Length", "Petal.Length")

{'x': 'Sepal.Length',
 'y': 'Petal.Length',
 'ppscore': 0.550422595049248,
 'case': 'regression',
 'is_valid_score': True,
 'metric': 'mean absolute error',
 'baseline_score': 1.4886666666666668,
 'model_score': 0.6692708968366863,
 'model': DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')}

In [32]:
#calculate the whole PPS matrix
pps.matrix(data)

,x,y,ppscore,case,is_valid_score,metric,baseline_score,model_score,model
0,Sepal.Length,Sepal.Length,1.000000,predict_itself,True,None,0.000000,1.000000,None
1,Sepal.Length,Sepal.Width,0.000000,regression,True,mean absolute error,0.330667,0.364704,"DecisionTreeRegressor(ccp_alpha=0.0, criterion..."
2,Sepal.Length,Petal.Length,0.550423,regression,True,mean absolute error,1.488667,0.669271,"DecisionTreeRegressor(ccp_alpha=0.0, criterion..."
3,Sepal.Length,Petal.Width,0.431739,regression,True,mean absolute error,0.644667,0.366339,"DecisionTreeRegressor(ccp_alpha=0.0, criterion..."
4,Sepal.Length,Species,0.471649,classification,True,weighted F1,0.353333,0.658333,"DecisionTreeClassifier(ccp_alpha=0.0, class_we..."
5,Sepal.Width,Sepal.Length,0.006966,regression,True,mean absolute error,0.684667,0.679897,"DecisionTreeRegressor(ccp_alpha=0.0, criterion..."
6,Sepal.Width,Sepal.Width,1.000000,predict_itself,True,None,0.000000,1.000000,None
7,Sepal.Width,Petal.Length,0.172375,regression,True,mean absolute error,1.488667,1.232058,"DecisionTreeRegressor(ccp_alpha=0.0, criterion..."
8,Sepal.Width,Petal.Width,0.132858,regression,True,mean absolute error,0.644667,0.559017,"DecisionTreeRegressor(ccp_alpha=0.0, criterion..."
9,Sepal.Width,Species,0.156915,classification,True,weighted F1,0.353333,0.454805,"DecisionTreeClassifier(ccp_alpha=0.0, class_we..."
10,Petal.Length,Sepal.Length,0.525617,regression,True,mean absolute error,0.684667,0.324794,"DecisionTreeRegressor(ccp_alpha=0.0, criterion..."
11,Petal.Length,Sepal.Width,0.052136,regression,True,mean absolute error,0.330667,0.313427,"DecisionTreeRegressor(ccp_alpha=0.0, criterion..."
12,Petal.Length,Petal.Length,1.000000,predict_itself,True,None,0.000000,1.000000,None
13,Petal.Length,Petal.Width,0.744945,regression,True,mean absolute error,0.644667,0.164425,"DecisionTreeRegressor(ccp_alpha=0.0, criterion..."
14,Petal.Length,Species,0.884812,classification,True,weighted F1,0.353333,0.925512,"DecisionTreeClassifier(ccp_alpha=0.0, class_we..."
15,Petal.Width,Sepal.Length,0.383911,regression,True,mean absolute error,0.684667,0.421816,"DecisionTreeRegressor(ccp_alpha=0.0, criterion..."
16,Petal.Width,Sepal.Width,0.254616,regression,True,mean absolute error,0.330667,0.246474,"DecisionTreeRegressor(ccp_alpha=0.0, criterion..."
17,Petal.Width,Petal.Length,0.798274,regression,True,mean absolute error,1.488667,0.300302,"DecisionTreeRegressor(ccp_alpha=0.0, criterion..."
18,Petal.Width,Petal.Width,1.000000,predict_itself,True,None,0.000000,1.000000,None
19,Petal.Width,Species,0.927652,classification,True,weighted F1,0.353333,0.953215,"DecisionTreeClassifier(ccp_alpha=0.0, class_we..."
20,Species,Sepal.Length,0.409634,regression,True,mean absolute error,0.684667,0.404204,"DecisionTreeRegressor(ccp_alpha=0.0, criterion..."
21,Species,Sepal.Width,0.194307,regression,True,mean absolute error,0.330667,0.266416,"DecisionTreeRegressor(ccp_alpha=0.0, criterion..."
22,Species,Petal.Length,0.785393,regression,True,mean absolute error,1.488667,0.319479,"DecisionTreeRegressor(ccp_alpha=0.0, criterion..."
23,Species,Petal.Width,0.755749,regression,True,mean absolute error,0.644667,0.157460,"DecisionTreeRegressor(ccp_alpha=0.0, criterion..."
24,Species,Species,1.000000,predict_itself,True,None,0.000000,1.000000,None